name: IAST
on:
  push:
    branches:
      - main
jobs:
  sast:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Force Java 17 for SonarScanner
        run: echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.8
        with:
          args: >
            -Dsonar.organization=henkyo
            -Dsonar.projectKey=HenkyO_PL_Tugas14_New
            -Dsonar.projectName=PL_Tugas14_New
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
